# Generated by Django 5.1.4 on 2025-03-25 05:56

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0003_remove_notification_manual_remove_notification_user_and_more'),
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True)),
                ('review_frequency_year', models.TextField(blank=True, null=True)),
                ('review_frequency_month', models.TextField(blank=True, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manual', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_manual', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='accounts.company')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_manual', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.manual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True)),
                ('review_frequency_year', models.TextField(blank=True, null=True)),
                ('review_frequency_month', models.TextField(blank=True, null=True)),
                ('relate_format', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procedure', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_procedure', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='accounts.company')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_procedure', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='RecordFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True)),
                ('review_frequency_year', models.TextField(blank=True, null=True)),
                ('review_frequency_month', models.TextField(blank=True, null=True)),
                ('retention', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_record', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkedrecord', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='accounts.company')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_record', to='company.users')),
            ],
        ),
    ]
