# Generated by Django 5.1.4 on 2025-03-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_policyenv'),
        ('qms', '0002_manual_notification_procedure_recordformat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificationQMS',
        ),
    ]
