# Generated by Django 5.1.4 on 2025-03-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0003_rename_notification_notificationqms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='send_notification',
        ),
    ]
