# Generated by Django 5.1.4 on 2025-03-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_policyenv'),
        ('qms', '0004_remove_manual_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionQMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_from', to='company.users')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_to', to='company.users')),
            ],
        ),
    ]
