# Generated by Django 5.1.4 on 2025-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0005_correctionqms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='document_type',
        ),
        migrations.AddField(
            model_name='manual',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval')], default='Pending for Review/Checking', max_length=50),
        ),
    ]
