# Generated by Django 5.1.4 on 2025-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0006_remove_manual_document_type_manual_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Approved', 'Approved')], default='Pending for Review/Checking', max_length=50),
        ),
    ]
