# Generated by Django 5.1.4 on 2025-03-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0007_alter_manual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionqms',
            name='manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.manual'),
        ),
    ]
