# Generated by Django 5.1.4 on 2025-03-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_policyenv'),
        ('qms', '0008_correctionqms_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionqms',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_from', to='company.users'),
        ),
        migrations.AlterField(
            model_name='correctionqms',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_to', to='company.users'),
        ),
    ]
