# Generated by Django 5.1.4 on 2025-03-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0012_remove_manual_correction_manual_corrections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='corrections',
        ),
        migrations.AddField(
            model_name='correctionqms',
            name='manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.manual'),
        ),
    ]
