# Generated by Django 5.1.4 on 2025-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0014_alter_manual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='document_type',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True),
        ),
    ]
