# Generated by Django 5.1.4 on 2025-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0015_manual_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationqms',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
