# Generated by Django 5.1.4 on 2025-03-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0016_notificationqms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
