# Generated by Django 5.1.4 on 2025-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0017_manual_approved_at_manual_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
