# Generated by Django 5.1.4 on 2025-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0018_manual_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
