# Generated by Django 5.1.4 on 2025-03-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0019_alter_manual_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydocumentation',
            name='user',
        ),
    ]
