# Generated by Django 5.1.4 on 2025-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0021_manual_send_email_to_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested')], default='Pending for Review/Checking', max_length=50),
        ),
    ]
