# Generated by Django 5.1.4 on 2025-04-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0023_manual_publish_manual_send_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='publish',
        ),
    ]
