# Generated by Django 5.1.4 on 2025-04-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_users_address_alter_users_answer_and_more'),
        ('qms', '0024_remove_manual_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='company.users'),
        ),
    ]
