# Generated by Django 5.1.4 on 2025-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0025_manual_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Publish', 'Publish')], default='Pending for Review/Checking', max_length=50),
        ),
    ]
