# Generated by Django 5.1.4 on 2025-04-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0027_manual_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='publish',
        ),
    ]
