# Generated by Django 5.1.4 on 2025-04-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0028_remove_manual_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='publish',
            new_name='is_draft',
        ),
        migrations.RenameField(
            model_name='recordformat',
            old_name='publish',
            new_name='is_draft',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='relate_format',
        ),
        migrations.RemoveField(
            model_name='recordformat',
            name='retention',
        ),
        migrations.AddField(
            model_name='procedure',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='send_email_to_approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedure',
            name='send_email_to_checked_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedure',
            name='send_notification_to_approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedure',
            name='send_notification_to_checked_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Publish', 'Publish')], default='Pending for Review/Checking', max_length=50),
        ),
        migrations.AddField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='company.users'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='send_email_to_approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='send_email_to_checked_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='send_notification_to_approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='send_notification_to_checked_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Publish', 'Publish')], default='Pending for Review/Checking', max_length=50),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='company.users'),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recordformat',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_record', to='company.users'),
        ),
        migrations.AlterField(
            model_name='recordformat',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
