# Generated by Django 5.1.4 on 2025-04-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0032_recordformat_retention_period_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificatioRecord',
            new_name='NotificationRecord',
        ),
    ]
