# Generated by Django 5.1.4 on 2025-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0033_rename_notificatiorecord_notificationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='related_record_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordformat',
            name='retention_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
