# Generated by Django 5.1.4 on 2025-04-11 06:06

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0034_alter_procedure_related_record_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_no', models.CharField(blank=True, max_length=50, null=True)),
                ('compliance_type', models.CharField(blank=True, choices=[('Legal', 'Legal'), ('Business', 'Business'), ('Client', 'Client'), ('Process/Specification', 'Process/Specification')], max_length=255, null=True)),
                ('attach_document', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('compliance_remarks', models.TextField(blank=True, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('compliance_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relate_business_process', models.CharField(blank=True, max_length=50, null=True)),
                ('relate_document', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
