# Generated by Django 5.1.4 on 2025-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0036_alter_manual_status_alter_procedure_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
