# Generated by Django 5.1.4 on 2025-04-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0037_manual_published_at_procedure_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='published_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_manual', to='company.users'),
        ),
    ]
