# Generated by Django 5.1.4 on 2025-04-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0038_manual_published_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='published_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_procedure', to='company.users'),
        ),
        migrations.AddField(
            model_name='recordformat',
            name='published_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_record', to='company.users'),
        ),
    ]
