# Generated by Django 5.1.4 on 2025-04-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('qms', '0039_procedure_published_user_recordformat_published_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='accounts.company'),
        ),
    ]
