# Generated by Django 5.1.4 on 2025-04-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('qms', '0040_compliance_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=20)),
                ('needs', models.TextField(blank=True, null=True)),
                ('expectations', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('legal_requirements', models.CharField(blank=True, choices=[('GDPR', 'GDPR'), ('HIPAA', 'HIPAA'), ('CCPA', 'CCPA'), ('SOX', 'SOX'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('custom_legal_requirements', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='qms/interested_parties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Interested Party',
                'verbose_name_plural': 'Interested Parties',
            },
        ),
    ]
