# Generated by Django 5.1.4 on 2025-04-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('qms', '0041_interestedparty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compliance',
            new_name='Compliances',
        ),
    ]
