# Generated by Django 5.1.4 on 2025-04-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0042_rename_compliance_compliances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliances',
            name='publish',
        ),
    ]
