# Generated by Django 5.1.4 on 2025-04-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0043_remove_compliances_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedparty',
            name='legal_requirements',
            field=models.CharField(blank=True, null=True),
        ),
    ]
