# Generated by Django 5.1.4 on 2025-04-12 05:26

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0044_alter_interestedparty_legal_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedparty',
            name='file',
            field=models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename),
        ),
    ]
