# Generated by Django 5.1.4 on 2025-04-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0045_alter_interestedparty_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedparty',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interestedparty',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
