# Generated by Django 5.1.4 on 2025-04-12 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0046_remove_interestedparty_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.interestedparty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='company.users')),
            ],
        ),
    ]
