# Generated by Django 5.1.4 on 2025-04-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0047_notificationinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationinterest',
            name='user',
        ),
    ]
