# Generated by Django 5.1.4 on 2025-04-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0048_remove_notificationinterest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparty',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
