# Generated by Django 5.1.4 on 2025-04-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0049_interestedparty_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='company.users'),
        ),
    ]
