# Generated by Django 5.1.4 on 2025-04-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0051_processes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processes',
            options={'verbose_name': 'Processes', 'verbose_name_plural': 'Processes'},
        ),
        migrations.CreateModel(
            name='NotificationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.processes')),
            ],
        ),
    ]
