# Generated by Django 5.1.4 on 2025-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0052_alter_processes_options_notificationprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
