# Generated by Django 5.1.4 on 2025-04-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0053_processes_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliances',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliances',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
