# Generated by Django 5.1.4 on 2025-04-16 06:40

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0012_alter_users_status'),
        ('qms', '0056_compliances_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_no', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True)),
                ('attach_document', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('related_record_format', models.CharField(blank=True, max_length=50, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.legalrequirement')),
            ],
        ),
    ]
