# Generated by Django 5.1.4 on 2025-04-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
        ('qms', '0060_notificationevaluation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationEvaluation',
            new_name='NotificationEvaluations',
        ),
    ]
