# Generated by Django 5.1.4 on 2025-04-17 03:19

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0012_alter_users_status'),
        ('qms', '0061_rename_notificationevaluation_notificationevaluations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('moc_type', models.CharField(blank=True, choices=[('Manual/Procedure', 'Manual/Procedure'), ('Guideline/Policy', 'Guideline/Policy'), ('Specification/Standards', 'Specification/Standards'), ('Facility/Equipment', 'Facility/Equipment'), ('System/Process', 'System/Process')], max_length=255, null=True)),
                ('attach_document', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('purpose_of_chnage', models.CharField(blank=True, max_length=50, null=True)),
                ('potential_cosequences', models.CharField(blank=True, max_length=50, null=True)),
                ('moc_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('moc_title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('related_record_format', models.CharField(blank=True, max_length=50, null=True)),
                ('resources_required', models.CharField(blank=True, max_length=50, null=True)),
                ('impact_on_process', models.CharField(blank=True, max_length=50, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='company.users')),
            ],
        ),
    ]
