# Generated by Django 5.1.4 on 2025-04-18 04:36

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0065_rename_sustainability_sustainabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('YouTube video', 'YouTube video'), ('Presentation', 'Presentation'), ('Web Link', 'Web Link')], max_length=255)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename1)),
                ('web_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
