# Generated by Django 5.1.4 on 2025-04-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0067_awarenesstraining_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesstraining',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awarenesstraining',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
