# Generated by Django 5.1.4 on 2025-04-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0068_awarenesstraining_is_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenesstraining',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='awarenesstraining',
            name='send_notification',
        ),
    ]
