# Generated by Django 5.1.4 on 2025-04-18 06:22

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0070_awarenesstraining_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliances',
            name='attach_document',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit),
        ),
    ]
