# Generated by Django 5.1.4 on 2025-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0071_alter_compliances_attach_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesstraining',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
