# Generated by Django 5.1.4 on 2025-04-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0072_awarenesstraining_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenesstraining',
            name='category',
            field=models.CharField(blank=True, choices=[('YouTube video', 'YouTube video'), ('Presentation', 'Presentation'), ('Web Link', 'Web Link')], max_length=255, null=True),
        ),
    ]
