# Generated by Django 5.1.4 on 2025-04-18 07:32

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_delete_training'),
        ('qms', '0073_alter_awarenesstraining_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=100)),
                ('expected_results', models.TextField(blank=True, null=True)),
                ('actual_results', models.TextField(blank=True, null=True)),
                ('type_of_training', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Client/Legal', 'Client/Legal'), ('Online', 'Online')], default='Internal', max_length=20)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('date_planned', models.DateField()),
                ('date_conducted', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_training)),
                ('training_evaluation', models.TextField(blank=True, null=True)),
                ('evaluation_date', models.DateField()),
                ('send_notification', models.BooleanField(default=False)),
                ('evaluation_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_by', to='company.users')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requested_by', to='company.users')),
                ('training_attendees', models.ManyToManyField(blank=True, related_name='training_attendees', to='company.users')),
            ],
        ),
    ]
