# Generated by Django 5.1.4 on 2025-04-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0014_delete_training'),
        ('qms', '0074_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='training',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='company.users'),
        ),
    ]
