# Generated by Django 5.1.4 on 2025-04-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_delete_training'),
        ('qms', '0076_trainingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingss', to='company.users'),
        ),
    ]
