# Generated by Django 5.1.4 on 2025-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_delete_training'),
        ('qms', '0077_trainingnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date_conducted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='date_planned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Completed', 'Completed')], default='Requested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='training_attendees', to='company.users'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='type_of_training',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External'), ('Client/Legal', 'Client/Legal'), ('Online', 'Online')], default='Internal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
