# Generated by Django 5.1.4 on 2025-04-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0079_alter_training_training_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_title', models.CharField(max_length=100)),
                ('valid_till', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
