# Generated by Django 5.1.4 on 2025-04-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0015_delete_employeeevaluation'),
        ('qms', '0080_employeeperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='company.users'),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='evaluation_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
