# Generated by Django 5.1.4 on 2025-04-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0081_employeeperformance_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer_text', models.CharField(blank=True, null=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qms.employeeperformance')),
            ],
        ),
    ]
