# Generated by Django 5.1.4 on 2025-04-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0082_performancequestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancequestions',
            old_name='answer_text',
            new_name='answer',
        ),
    ]
