# Generated by Django 5.1.4 on 2025-04-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0084_performancequestions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancequestions',
            name='user',
        ),
    ]
