# Generated by Django 5.1.4 on 2025-04-19 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_delete_employeeevaluation'),
        ('qms', '0085_remove_performancequestions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancequestions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='company.users'),
        ),
    ]
