# Generated by Django 5.1.4 on 2025-04-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0087_employeesurvey_surveyquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestions',
            old_name='performance',
            new_name='survey',
        ),
    ]
