# Generated by Django 5.1.4 on 2025-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0089_alter_awarenesstraining_upload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocumentation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
