# Generated by Django 5.1.4 on 2025-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0091_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='legal_requirements',
        ),
        migrations.AddField(
            model_name='processes',
            name='legal_requirements',
            field=models.ManyToManyField(blank=True, related_name='processes', to='qms.procedure'),
        ),
    ]
