# Generated by Django 5.1.4 on 2025-04-23 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0017_delete_meeting'),
        ('qms', '0092_remove_processes_legal_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('Normal', 'Normal'), ('Specific', 'Specific')], default='Normal', max_length=50)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('agenda', models.ManyToManyField(blank=True, related_name='meeting_agenda', to='qms.agenda')),
                ('attendees', models.ManyToManyField(blank=True, related_name='meeting_attendees', to='company.users')),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_meeting', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='company.users')),
            ],
        ),
    ]
