# Generated by Django 5.1.4 on 2025-04-23 10:26

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0094_meetingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
