# Generated by Django 5.1.4 on 2025-04-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0095_meeting_file_meeting_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
