# Generated by Django 5.1.4 on 2025-04-24 05:55

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0019_delete_audit'),
        ('qms', '0097_cause_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_from', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('certification_body', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50)),
                ('date_conducted', models.DateField(blank=True, null=True)),
                ('upload_audit_report', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('upload_non_coformities_report', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('is_draft', models.BooleanField(default=False)),
                ('audit_from_internal', models.ManyToManyField(blank=True, related_name='users', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_company', to='accounts.company')),
                ('procedures', models.ManyToManyField(blank=True, related_name='procedures', to='qms.procedure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='company.users')),
            ],
        ),
    ]
