# Generated by Django 5.1.4 on 2025-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0098_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50, null=True),
        ),
    ]
