# Generated by Django 5.1.4 on 2025-04-25 05:01

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0020_delete_inspection'),
        ('qms', '0099_alter_audit_audit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('inspector_from', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('certification_body', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_type', models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50, null=True)),
                ('date_conducted', models.DateField(blank=True, null=True)),
                ('upload_inspection_report', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('upload_non_coformities_report', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspention_company', to='accounts.company')),
                ('inspector_from_internal', models.ManyToManyField(blank=True, related_name='inspector_users', to='company.users')),
                ('procedures', models.ManyToManyField(blank=True, related_name='insprocedures', to='qms.procedure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspention', to='company.users')),
            ],
        ),
    ]
