# Generated by Django 5.1.4 on 2025-04-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('qms', '0101_carnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnumber',
            old_name='action',
            new_name='action_no',
        ),
        migrations.AddField(
            model_name='carnumber',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnumber', to='accounts.company'),
        ),
    ]
