# Generated by Django 5.1.4 on 2025-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0102_rename_action_carnumber_action_no_carnumber_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
