# Generated by Django 5.1.4 on 2025-04-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0104_carnotification_rootcause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='root_cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.rootcause'),
        ),
    ]
