# Generated by Django 5.1.4 on 2025-04-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0105_alter_carnumber_root_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='root_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carroot', to='qms.rootcause'),
        ),
    ]
