# Generated by Django 5.1.4 on 2025-04-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0023_remove_environmentalincidents_root_cause_and_more'),
        ('qms', '0106_alter_carnumber_root_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, null=True)),
                ('immediate_action', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('solve_after_action', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('corrective_action', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('correction', models.TextField(blank=True, null=True)),
                ('car_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_car', to='qms.carnumber')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_cause', to='qms.cause')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_com', to='accounts.company')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_executor', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal', to='company.users')),
            ],
        ),
    ]
