# Generated by Django 5.1.4 on 2025-04-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0107_internalproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='source',
            field=models.CharField(blank=True, choices=[('Audit', 'Audit'), ('Customer', 'Customer'), ('Internal', 'Internal'), ('Supplier', 'Supplier')], max_length=255, null=True),
        ),
    ]
