# Generated by Django 5.2 on 2025-04-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0111_supplier_is_draft_supplierproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproblem',
            name='is_draft',
        ),
    ]
