# Generated by Django 5.2 on 2025-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0112_remove_supplierproblem_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproblem',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
