# Generated by Django 5.2 on 2025-04-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0113_supplierproblem_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_draft',
        ),
    ]
