# Generated by Django 5.2 on 2025-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0114_remove_supplier_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
