# Generated by Django 5.2 on 2025-04-28 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0115_supplier_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedparty',
            name='expectations',
        ),
        migrations.RemoveField(
            model_name='interestedparty',
            name='needs',
        ),
        migrations.CreateModel(
            name='Expectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('interested_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expectation', to='qms.interestedparty')),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('interested_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='qms.interestedparty')),
            ],
        ),
    ]
