# Generated by Django 5.2 on 2025-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0116_remove_interestedparty_expectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type_of_training',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External'), ('Legal/Regulatory', 'Legal/Regulatory'), ('Client', 'Client'), ('Online', 'Online')], default='Internal', max_length=20, null=True),
        ),
    ]
