# Generated by Django 5.2 on 2025-04-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0025_delete_supplierproblem'),
        ('qms', '0117_alter_training_type_of_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproblem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_com_problem', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='supplierproblem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_problem', to='company.users'),
        ),
    ]
