# Generated by Django 5.2 on 2025-04-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0118_supplierproblem_company_supplierproblem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproblem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_pr', to='qms.supplier'),
        ),
    ]
