# Generated by Django 5.2 on 2025-04-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_delete_supplierproblem'),
        ('qms', '0121_supplierevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEvaluationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, null=True)),
                ('supp_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supp_evlua', to='qms.supplierevaluation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveqsn_supp', to='company.users')),
            ],
        ),
    ]
