# Generated by Django 5.2 on 2025-04-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0126_category_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestions',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supp_evlua', to='qms.customersatisfaction'),
        ),
    ]
