# Generated by Django 5.2 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0127_alter_customerquestions_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needs',
            old_name='title',
            new_name='expectation',
        ),
        migrations.AddField(
            model_name='needs',
            name='needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Expectations',
        ),
    ]
