# Generated by Django 5.2 on 2025-05-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0128_rename_title_needs_expectation_needs_needs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierevaluationquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='supplierevaluationquestions',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveqsn_supp', to='qms.supplier'),
        ),
    ]
