# Generated by Django 5.2 on 2025-05-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0129_remove_supplierevaluationquestions_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='customerquestions',
            name='customer_qsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='us_user', to='qms.customer'),
        ),
    ]
