# Generated by Django 5.2 on 2025-05-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0027_delete_customersatisfaction_delete_question'),
        ('qms', '0131_alter_evaluation_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTrainingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_title', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bbbbb', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaaa', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTrainingEvaluationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, null=True)),
                ('emp_training_eval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddd', to='qms.employeetrainingevaluation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccc', to='company.users')),
            ],
        ),
    ]
