# Generated by Django 5.2 on 2025-05-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0133_replaymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.supplier'),
        ),
    ]
