# Generated by Django 5.2 on 2025-05-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_delete_customersatisfaction_delete_question'),
        ('qms', '0134_carnumber_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_carn', to='company.users'),
        ),
    ]
