# Generated by Django 5.2 on 2025-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0135_carnumber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='type',
            field=models.CharField(choices=[('Strategic', 'Strategic'), ('Core', 'Core'), ('Support', 'Support'), ('Monitoring/Measurment', 'Monitoring/Measurment'), ('Outsource', 'Outsource')], default='Stratgic', max_length=50),
        ),
    ]
