# Generated by Django 5.2 on 2025-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_delete_customersatisfaction_delete_question'),
        ('qms', '0136_alter_processes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to='company.users'),
        ),
    ]
