# Generated by Django 5.2 on 2025-05-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0137_remove_message_to_user_message_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaymessage',
            name='message_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess_com', to='qms.message'),
        ),
    ]
