# Generated by Django 5.2 on 2025-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0139_forwardmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
