# Generated by Django 5.2 on 2025-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0140_message_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardmessage',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replaymessage',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
