# Generated by Django 5.2 on 2025-05-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0141_forwardmessage_is_trash_replaymessage_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
