# Generated by Django 5.2 on 2025-05-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_delete_preventiveaction'),
        ('qms', '0143_preventiveaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveActionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preventive_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.preventiveaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventive_action', to='company.users')),
            ],
        ),
    ]
