# Generated by Django 5.2 on 2025-05-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0029_delete_objectives'),
        ('qms', '0144_preventiveactionnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(blank=True, max_length=255, null=True)),
                ('performance', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Going', 'On Going'), ('Achieved', 'Achieved'), ('Not Achieved', 'Not Achieved'), ('Modified', 'Modified')], default='On Going', max_length=20)),
                ('indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_cus', to='accounts.company')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_planobjectives', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='company.users')),
            ],
        ),
    ]
