# Generated by Django 5.2 on 2025-05-07 10:30

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0030_remove_tprogram_targets_delete_targetsp_and_more'),
        ('qms', '0145_objectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('associative_objective', models.CharField(blank=True, max_length=50, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Going', 'On Going'), ('Achieved', 'Achieved'), ('Not Achieved', 'Not Achieved'), ('Modified', 'Modified')], default='On Going', max_length=20)),
                ('results', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tar_cus', to='accounts.company')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_targets', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traget', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(blank=True, max_length=50, null=True)),
                ('targets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='qms.targets')),
            ],
        ),
    ]
