# Generated by Django 5.2 on 2025-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0146_targets_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='targets',
            new_name='target',
        ),
    ]
