# Generated by Django 5.2 on 2025-05-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0147_rename_targets_program_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
