# Generated by Django 5.2 on 2025-05-08 06:12

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0032_delete_energyreview_delete_reviewtype'),
        ('qms', '0151_conformitynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_no', models.IntegerField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('energy_name', models.CharField(blank=True, max_length=50, null=True)),
                ('relate_business_process', models.CharField(blank=True, max_length=20, null=True)),
                ('relate_document_process', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_cus', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReviewNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.energyreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_user', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_rt', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='energyreview',
            name='review_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.reviewtype'),
        ),
    ]
