# Generated by Django 5.2 on 2025-05-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0033_remove_baseline_energy_review_and_more'),
        ('qms', '0152_energyreview_energyreviewnotification_reviewtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basline_title', models.CharField(blank=True, max_length=50, null=True)),
                ('established_basline', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_cus', to='accounts.company')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_baseline', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_use', to='company.users')),
                ('energy_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.baselinereview')),
            ],
        ),
        migrations.CreateModel(
            name='Enpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enpi', models.CharField(blank=True, max_length=50, null=True)),
                ('baseline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enpis', to='qms.baseline')),
            ],
        ),
    ]
