# Generated by Django 5.2 on 2025-05-08 09:01

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0034_delete_energyimprovement'),
        ('qms', '0153_baselinereview_baseline_enpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eio', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Going', 'On Going'), ('Achieved', 'Achieved'), ('Not Achieved', 'Not Achieved'), ('Modified', 'Modified')], default='On Going', max_length=20)),
                ('eio_title', models.CharField(blank=True, max_length=50, null=True)),
                ('associated_objective', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ene_cus', to='accounts.company')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_energy_improvements', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ene_use', to='company.users')),
            ],
        ),
    ]
