# Generated by Django 5.2 on 2025-05-08 09:23

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0035_remove_program_energy_action_delete_energyaction_and_more'),
        ('qms', '0154_energyimprovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyimprovement',
            name='upload_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit),
        ),
        migrations.AlterField(
            model_name='energyreview',
            name='upload_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit),
        ),
        migrations.CreateModel(
            name='EnergyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('associative_objective', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_requirements', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('energy_improvements', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('means', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_cus', to='accounts.company')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_energy_action_plan', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_use', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='qms.energyaction')),
            ],
        ),
    ]
