# Generated by Django 5.2 on 2025-05-08 09:45

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0036_remove_significantenergy_source_type_and_more'),
        ('qms', '0155_alter_energyimprovement_upload_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='SignificantEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significant', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('consequences', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('impact', models.CharField(blank=True, max_length=50, null=True)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('is_notification', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_cus', to='accounts.company')),
                ('source_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.energysource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_use', to='company.users')),
            ],
        ),
    ]
