# Generated by Django 5.2 on 2025-05-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0156_energysource_significantenergy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='significantenergy',
            old_name='rivision',
            new_name='revision',
        ),
    ]
