# Generated by Django 5.2 on 2025-05-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_significantenergy_source_type_and_more'),
        ('qms', '0157_rename_rivision_significantenergy_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantEnergyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('significant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.significantenergy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sig_user', to='company.users')),
            ],
        ),
    ]
