# Generated by Django 5.2 on 2025-05-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_significantenergy_source_type_and_more'),
        ('qms', '0158_significantenergynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trash_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash_message_user', to='company.users'),
        ),
    ]
