# Generated by Django 5.2 on 2025-05-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_significantenergy_source_type_and_more'),
        ('qms', '0159_message_trash_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardmessage',
            name='trash_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forard_message_user', to='company.users'),
        ),
        migrations.AddField(
            model_name='replaymessage',
            name='trash_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_message_user', to='company.users'),
        ),
    ]
