# Generated by Django 5.2 on 2025-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0160_forwardmessage_trash_user_replaymessage_trash_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='ProgramAction',
        ),
    ]
