# Generated by Django 5.2 on 2025-05-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0162_processactivity_environmentalaspect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalaspect',
            old_name='aspect',
            new_name='aspect_no',
        ),
    ]
