# Generated by Django 5.2 on 2025-05-09 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_remove_environmentalaspect_approved_by_and_more'),
        ('qms', '0163_rename_aspect_environmentalaspect_aspect_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalaspect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_aspect', to='company.users')),
            ],
        ),
    ]
