# Generated by Django 5.2 on 2025-05-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_remove_environmentalaspect_approved_by_and_more'),
        ('qms', '0164_notificationaspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aspect_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalaspect')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asp_from', to='company.users')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_asp', to='company.users')),
            ],
        ),
    ]
