# Generated by Django 5.2 on 2025-05-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0165_correctionaspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalaspect',
            name='status',
            field=models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Published', 'Published')], default='Pending for Review/Checking', max_length=50),
        ),
    ]
