# Generated by Django 5.2 on 2025-05-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0167_remove_correctionaspect_aspect_correction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalimpact',
            old_name='attach_document',
            new_name='upload_attachment',
        ),
    ]
