# Generated by Django 5.2 on 2025-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0168_rename_attach_document_environmentalimpact_upload_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalimpact',
            name='review_frequency_month',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentalimpact',
            name='review_frequency_year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
