# Generated by Django 5.2 on 2025-05-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_delete_environmentalimpact'),
        ('qms', '0169_environmentalimpact_review_frequency_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctionaspect',
            name='impact_correction',
        ),
        migrations.AddField(
            model_name='correctionaspect',
            name='aspect_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalaspect'),
        ),
        migrations.AlterField(
            model_name='correctionaspect',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asp_from', to='company.users'),
        ),
        migrations.AlterField(
            model_name='correctionaspect',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_asp', to='company.users'),
        ),
        migrations.CreateModel(
            name='CorrectionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imp_from', to='company.users')),
                ('impact_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalimpact')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_imp', to='company.users')),
            ],
        ),
    ]
