# Generated by Django 5.2 on 2025-05-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0170_remove_correctionaspect_impact_correction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationimpact',
            old_name='imapct',
            new_name='impact',
        ),
    ]
