# Generated by Django 5.2 on 2025-05-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0040_delete_environmentalwaste'),
        ('qms', '0173_incidentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmp', models.CharField(blank=True, max_length=50, null=True)),
                ('originator', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_type', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_quantity', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_handling', models.CharField(blank=True, choices=[('Company', 'Company'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('Third Party/Others', 'Third Party/Others')], max_length=255, null=True)),
                ('waste_category', models.CharField(blank=True, choices=[('Hazardous', 'Hazardous'), ('Non Hazardous', 'Non Hazardous')], max_length=255, null=True)),
                ('waste_minimization', models.CharField(blank=True, choices=[('Reuse', 'Reuse'), ('Recycle', 'Recycle'), ('Recovery', 'Recovery'), ('Disposal', 'Disposal'), ('Non Disposable', 'Non Disposable')], max_length=255, null=True)),
                ('responsible_party', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('written_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('send_notification_to_checked_by', models.BooleanField(default=False)),
                ('send_email_to_checked_by', models.BooleanField(default=False)),
                ('send_notification_to_approved_by', models.BooleanField(default=False)),
                ('send_email_to_approved_by', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Published', 'Published')], default='Pending for Review/Checking', max_length=100)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waste', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_waste', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lst', to='accounts.company')),
                ('published_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_wastes', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastes_user', to='company.users')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_wasrter', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='was_from', to='company.users')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_was', to='company.users')),
                ('waste_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalwaste')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_waste', to='company.users')),
                ('waste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.environmentalwaste')),
            ],
        ),
    ]
