# Generated by Django 5.2 on 2025-05-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0174_environmentalwaste_correctionwaste_notificationwaste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalwaste',
            name='send_notification',
        ),
    ]
