# Generated by Django 5.2 on 2025-05-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('qms', '0175_remove_environmentalwaste_send_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_cause', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='interestedparty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cause', to='qms.causeparty'),
        ),
    ]
