# Generated by Django 5.2 on 2025-05-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0041_remove_healthsafety_approved_by_and_more'),
        ('qms', '0176_causeparty_interestedparty_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_source', models.CharField(blank=True, max_length=50, null=True)),
                ('hazard_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('level_of_risk', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('written_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('send_notification_to_checked_by', models.BooleanField(default=False)),
                ('send_email_to_checked_by', models.BooleanField(default=False)),
                ('send_notification_to_approved_by', models.BooleanField(default=False)),
                ('send_email_to_approved_by', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Published', 'Published')], default='Pending for Review/Checking', max_length=100)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hazard', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_hazard', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_lst', to='accounts.company')),
                ('published_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_publish', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_user', to='company.users')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_hazard', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_from', to='company.users')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_health', to='company.users')),
                ('health_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.healthsafety')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.healthsafety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_healthe', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_type', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='healthsafety',
            name='process_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.processhealth'),
        ),
    ]
