# Generated by Django 5.2 on 2025-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0177_healthsafety_correctionhealth_notificationhealth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyreview',
            name='review_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
