# Generated by Django 5.2 on 2025-05-12 08:22

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0042_delete_riskassessment'),
        ('qms', '0178_alter_energyreview_review_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('related_record_format', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('System', 'System'), ('Paper', 'Paper'), ('External', 'External'), ('Work Instruction', 'Work Instruction')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit)),
                ('rivision', models.CharField(blank=True, max_length=50, null=True)),
                ('written_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('send_notification_to_checked_by', models.BooleanField(default=False)),
                ('send_email_to_checked_by', models.BooleanField(default=False)),
                ('send_notification_to_approved_by', models.BooleanField(default=False)),
                ('send_email_to_approved_by', models.BooleanField(default=False)),
                ('review_frequency_year', models.TextField(blank=True, null=True)),
                ('review_frequency_month', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending for Review/Checking', 'Pending for Review/Checking'), ('Reviewed,Pending for Approval', 'Reviewed,Pending for Approval'), ('Pending for Publish', 'Pending for Publish'), ('Correction Requested', 'Correction Requested'), ('Published', 'Published')], default='Pending for Review/Checking', max_length=100)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessment', to='company.users')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_assessment', to='company.users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assess_lst', to='accounts.company')),
                ('published_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assess_publish', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assess_user', to='company.users')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_assessment', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAssessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_assess', to='company.users')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionAssessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assess_from', to='company.users')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_assess', to='company.users')),
                ('assessment_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.riskassessment')),
            ],
        ),
    ]
