# Generated by Django 5.2 on 2025-05-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0179_riskassessment_notificationassessments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heal_lst', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='HealthIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('incident_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
                ('action', models.TextField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healinc_lst', to='accounts.company')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_health_incidents', to='company.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healinc_user', to='company.users')),
                ('root_cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.healthrootcause')),
            ],
        ),
    ]
