# Generated by Django 5.2 on 2025-05-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0180_healthrootcause_healthincidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHealthIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('safety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.healthincidents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_safety', to='company.users')),
            ],
        ),
    ]
