# Generated by Django 5.2 on 2025-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0181_notificationhealthincidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyimprovement',
            name='eio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
