# Generated by Django 5.2 on 2025-05-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0182_alter_energyimprovement_eio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20, null=True),
        ),
    ]
