# Generated by Django 5.2 on 2025-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0183_alter_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocumentation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
