# Generated by Django 5.2 on 2025-05-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0184_alter_policydocumentation_title_alter_scope_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaymessage',
            name='reply_to_replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_replies', to='qms.replaymessage'),
        ),
        migrations.AlterField(
            model_name='replaymessage',
            name='message_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qms.message'),
        ),
    ]
