# Generated by Django 5.2 on 2025-05-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0185_replaymessage_reply_to_replay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaymessage',
            name='reply_to_replay',
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='qms.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='qms.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='company.users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trash_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trashed_messages', to='company.users'),
        ),
        migrations.AlterField(
            model_name='replaymessage',
            name='message_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess_com', to='qms.message'),
        ),
    ]
