# Generated by Django 5.2 on 2025-05-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0186_remove_replaymessage_reply_to_replay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaymessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='message_related',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='to_users',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='trash_user',
        ),
        migrations.DeleteModel(
            name='ForwardMessage',
        ),
        migrations.DeleteModel(
            name='ReplayMessage',
        ),
    ]
