# Generated by Django 5.2 on 2025-05-16 07:36

import django.db.models.deletion
import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0187_remove_replaymessage_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to='company.users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trash_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash_message_user', to='company.users'),
        ),
        migrations.CreateModel(
            name='ForwardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename)),
                ('message', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_trash', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_for', to='accounts.company')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_for', to='company.users')),
                ('message_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess_for', to='qms.message')),
                ('to_users', models.ManyToManyField(blank=True, related_name='received_replay_messages_for', to='company.users')),
                ('trash_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forard_message_user', to='company.users')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename)),
                ('message', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_trash', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_com', to='accounts.company')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_users', to='company.users')),
                ('message_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess_com', to='qms.message')),
                ('to_users', models.ManyToManyField(blank=True, related_name='received_replay_messages', to='company.users')),
                ('trash_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_message_user', to='company.users')),
            ],
        ),
    ]
