# Generated by Django 5.2 on 2025-05-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0188_remove_message_forwarded_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaymessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='message_related',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='to_users',
        ),
        migrations.RemoveField(
            model_name='replaymessage',
            name='trash_user',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='qms.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='qms.message'),
        ),
        migrations.DeleteModel(
            name='ForwardMessage',
        ),
        migrations.DeleteModel(
            name='ReplayMessage',
        ),
    ]
