# Generated by Django 5.2 on 2025-05-19 04:37

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0189_remove_replaymessage_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='upload_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit),
        ),
    ]
