# Generated by Django 5.2 on 2025-05-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0190_alter_complaints_upload_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='qualified_to_supply',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
