# Generated by Django 5.2 on 2025-05-22 03:04

import qms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0192_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='upload_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, storage=qms.models.MediaStorage(), upload_to=qms.models.generate_unique_filename_audit),
        ),
    ]
