# Generated by Django 5.2 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0194_compliancenotification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancenotification',
            name='user',
        ),
        migrations.AddField(
            model_name='compliancenotification',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='c_notifications', to='company.users'),
        ),
    ]
