# Generated by Django 5.2 on 2025-05-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0196_remove_compliancenotification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationinterest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int', to='company.users'),
        ),
    ]
