# Generated by Django 5.2 on 2025-05-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_delete_healthincidents_delete_healthrootcause'),
        ('qms', '0198_notificationprocess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlegal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leg', to='company.users'),
        ),
    ]
