from django.contrib import admin
from .models import *
 


admin.site.register(PolicyDocumentation)
admin.site.register(Manual)
admin.site.register(Procedure)
admin.site.register(RecordFormat)
admin.site.register(NotificationQMS)
admin.site.register(CorrectionQMS)
admin.site.register(NotificatioProcedure)
admin.site.register(CorrectionProcedure)
admin.site.register(NotificationRecord)
admin.site.register(CorrectionRecord)
admin.site.register(Compliances)
admin.site.register(InterestedParty)
admin.site.register(Needs)
admin.site.register(Expectations)
admin.site.register(NotificationInterest)
admin.site.register(Processes)
admin.site.register(NotificationProcess)
admin.site.register(ComplianceNotification)
admin.site.register(LegalRequirement)
admin.site.register(NotificationLegal)
admin.site.register(Evaluation)
admin.site.register(CorrectionEvaluation)
admin.site.register(NotificationEvaluations)
admin.site.register(ManagementChanges)
admin.site.register(NotificationChanges)
admin.site.register(Sustainabilities)
admin.site.register(CorrectionSustainability)
admin.site.register(NotificationSustainability)
admin.site.register(AwarenessTraining)
admin.site.register(Training)
admin.site.register(TrainingNotification)
admin.site.register(EmployeePerformance)
admin.site.register(PerformanceQuestions)
admin.site.register(EmployeeSurvey)
admin.site.register(SurveyQuestions)
admin.site.register(Scope)
admin.site.register(Agenda)
admin.site.register(Meeting)
admin.site.register(MeetingNotification)
admin.site.register(Message)
admin.site.register(Audit)
admin.site.register(Inspection)
admin.site.register(Cause)
admin.site.register(RootCause)
admin.site.register(CarNumber)
admin.site.register(CarNotification)
admin.site.register(InternalProblem)
admin.site.register(Supplier)
admin.site.register(SupplierProblem)