# Generated by Django 5.1.4 on 2025-03-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyDocumentation',
        ),
    ]
