# Generated by Django 5.1.4 on 2025-03-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_policydocumentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='written_by',
        ),
        migrations.RemoveField(
            model_name='recordformat',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='recordformat',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='recordformat',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recordformat',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='Manual',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='RecordFormat',
        ),
    ]
