# Generated by Django 5.1.4 on 2025-03-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_notification_manual_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyEnv',
        ),
    ]
