# Generated by Django 5.1.4 on 2025-04-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
    ]
