# Generated by Django 5.1.4 on 2025-04-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
