# Generated by Django 5.1.4 on 2025-04-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=20),
        ),
    ]
