# Generated by Django 5.1.4 on 2025-04-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_users_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwarenessTraining',
        ),
        migrations.RemoveField(
            model_name='sustainability',
            name='sustainability_no',
        ),
        migrations.RemoveField(
            model_name='complianceevaluation',
            name='compliance_no',
        ),
        migrations.RemoveField(
            model_name='complianceevaluation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='complianceevaluation',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='complianceevaluation',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='LegalRequirements',
        ),
        migrations.DeleteModel(
            name='ManagementChange',
        ),
        migrations.RemoveField(
            model_name='policyams',
            name='company',
        ),
        migrations.RemoveField(
            model_name='policyams',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policybms',
            name='company',
        ),
        migrations.RemoveField(
            model_name='policybms',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policyenms',
            name='company',
        ),
        migrations.RemoveField(
            model_name='policyenms',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policyims',
            name='company',
        ),
        migrations.RemoveField(
            model_name='policyims',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policyohs',
            name='company',
        ),
        migrations.RemoveField(
            model_name='policyohs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sustainability',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='sustainability',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='sustainability',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='Compliance',
        ),
        migrations.DeleteModel(
            name='ComplianceEvaluation',
        ),
        migrations.DeleteModel(
            name='PolicyAMS',
        ),
        migrations.DeleteModel(
            name='PolicyBMS',
        ),
        migrations.DeleteModel(
            name='PolicyEnms',
        ),
        migrations.DeleteModel(
            name='PolicyIMS',
        ),
        migrations.DeleteModel(
            name='PolicyOhs',
        ),
        migrations.DeleteModel(
            name='Sustainability',
        ),
    ]
