# Generated by Django 5.1.4 on 2025-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_delete_awarenesstraining_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
    ]
