# Generated by Django 5.1.4 on 2025-04-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_delete_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeEvaluation',
        ),
    ]
