# Generated by Django 5.1.4 on 2025-04-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_delete_employeesurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
