# Generated by Django 5.1.4 on 2025-04-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_delete_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
