# Generated by Django 5.1.4 on 2025-04-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_delete_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
