# Generated by Django 5.1.4 on 2025-04-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
