# Generated by Django 5.1.4 on 2025-04-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_delete_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalproblems',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='internalproblems',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='internalproblems',
            name='no_car',
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='InternalProblems',
        ),
    ]
