# Generated by Django 5.1.4 on 2025-04-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_remove_internalproblems_cause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='no_car',
        ),
        migrations.RemoveField(
            model_name='supplierproblem',
            name='no_car',
        ),
        migrations.DeleteModel(
            name='CarNumber',
        ),
    ]
