# Generated by Django 5.1.4 on 2025-04-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_remove_complaints_no_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalincidents',
            name='root_cause',
        ),
        migrations.DeleteModel(
            name='RootCause',
        ),
    ]
