# Generated by Django 5.1.4 on 2025-04-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_remove_environmentalincidents_root_cause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproblem',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
