# Generated by Django 5.1.4 on 2025-04-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_remove_supplierproblem_supplier_delete_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierProblem',
        ),
    ]
