# Generated by Django 5.2 on 2025-04-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_delete_supplierproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='customersatisfaction',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
