# Generated by Django 5.2 on 2025-04-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_remove_complaints_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSatisfaction',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
