# Generated by Django 5.2 on 2025-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_delete_customersatisfaction_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreventiveAction',
        ),
    ]
