# Generated by Django 5.2 on 2025-05-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_delete_preventiveaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objectives',
        ),
    ]
