# Generated by Django 5.2 on 2025-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_delete_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tprogram',
            name='targets',
        ),
        migrations.DeleteModel(
            name='TargetsP',
        ),
        migrations.DeleteModel(
            name='TProgram',
        ),
    ]
