# Generated by Django 5.2 on 2025-05-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_remove_tprogram_targets_delete_targetsp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conformity',
        ),
        migrations.DeleteModel(
            name='ConformityCause',
        ),
    ]
