# Generated by Django 5.2 on 2025-05-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_delete_conformity_delete_conformitycause'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyReview',
        ),
        migrations.DeleteModel(
            name='ReviewType',
        ),
    ]
