# Generated by Django 5.2 on 2025-05-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_delete_energyreview_delete_reviewtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseline',
            name='energy_review',
        ),
        migrations.RemoveField(
            model_name='baseline',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='enpis',
            name='baseline',
        ),
        migrations.DeleteModel(
            name='BaselineReview',
        ),
        migrations.DeleteModel(
            name='Baseline',
        ),
        migrations.DeleteModel(
            name='Enpis',
        ),
    ]
