# Generated by Django 5.2 on 2025-05-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_baseline_energy_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyImprovement',
        ),
    ]
