# Generated by Django 5.2 on 2025-05-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_delete_energyimprovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='energy_action',
        ),
        migrations.DeleteModel(
            name='EnergyAction',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
