# Generated by Django 5.2 on 2025-05-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_remove_program_energy_action_delete_energyaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='significantenergy',
            name='source_type',
        ),
        migrations.DeleteModel(
            name='EnergySource',
        ),
        migrations.DeleteModel(
            name='SignificantEnergy',
        ),
    ]
