# Generated by Django 5.2 on 2025-05-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_significantenergy_source_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalaspect',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='environmentalaspect',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='environmentalaspect',
            name='process_activity',
        ),
        migrations.RemoveField(
            model_name='environmentalaspect',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='ProcessActivity',
        ),
        migrations.DeleteModel(
            name='EnvironmentalAspect',
        ),
    ]
