# Generated by Django 5.2 on 2025-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_remove_environmentalaspect_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalImpact',
        ),
    ]
