# Generated by Django 5.2 on 2025-05-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_delete_environmentalimpact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalIncidents',
        ),
    ]
