# Generated by Django 5.2 on 2025-05-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_delete_environmentalincidents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalWaste',
        ),
    ]
