# Generated by Django 5.2 on 2025-05-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_delete_environmentalwaste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthsafety',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='healthsafety',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='healthsafety',
            name='process_activity',
        ),
        migrations.RemoveField(
            model_name='healthsafety',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='ProcessHealth',
        ),
        migrations.DeleteModel(
            name='HealthSafety',
        ),
    ]
