# Generated by Django 5.2 on 2025-05-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_remove_healthsafety_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
    ]
