# Generated by Django 5.2 on 2025-05-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_delete_riskassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthIncidents',
        ),
        migrations.DeleteModel(
            name='HealthRootCause',
        ),
    ]
